//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Case_Study
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonu
    {
        public long Bonid { get; set; }
        public System.DateTime Bondate { get; set; }
        public long Bonamount { get; set; }
        public long Empid { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
